version: '3.9'
services:
  openethereum:
    init: true
    user: root
    restart: unless-stopped
    container_name: kitabu-openethereum
    image: openethereum/openethereum:v3.3.3
    command:
      --config=/root/kitabu.toml
      --nat='extip:$EXT_IP'
      --engine-signer='$ACCOUNT'
      --jsonrpc-port=8545
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=web3,eth,net,parity
      --ws-port=8546
      --ws-interface=all
      --ws-hosts=all
      --bootnodes=enode://0f0741b4244cc88d3fa275a37c30da4455d2bfcc8472519772dafcbf039b156ff2defa661088a071c9128139329c4c510bcd42f706f6f9e0bf8a5735e3bc0ac0@165.22.126.72:30303,enode://81957cebe2dea51c245b8df4f18de4a19d709e7551ba3398e3da33291025c1cbf5edf9c0c585765b73c5ed6777b3274a5df803a04438e022b7a6016d333398f4@142.93.38.53:30303,enode://76ca34f5cd3ea363ba9a4110faa09c02e7e4c626279a71f45ac48fc7bb90a532aaeb383492f68b5ed968ece954b37cb787857f8d58436eda4e864047e0be34b2@143.244.142.41:30303
    volumes:
      - ./key:/root/data/keys/kitabu_sarafu/key
      - ./kitabu.json:/root/kitabu.json
      - ./kitabu.toml:/root/kitabu.toml
      - ./password:/root/password
      - ./data:/root/data
    expose:
      - '8545'
      - '8546'
    ports:
      - '30303:30303'
      - '30303:30303/udp'
    networks:
      - kitabu
networks:
  kitabu:
    driver: bridge
