version: '3.9'
services:
  openethereum:
    init: true
    user: root
    restart: unless-stopped
    container_name: kitabu-openethereum
    image: openethereum/openethereum:v3.3.3
    command:
      --config=/root/kitabu.toml
      --nat='extip:$EXT_IP'
      --engine-signer='$ACCOUNT'
      --jsonrpc-port=8545
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=web3,eth,net,parity
      --ws-port=8546
      --ws-interface=all
      --ws-hosts=all
      --bootnodes=enode://af55fdbfdf8c31d7550082f28050ab0b9a10c3763dda2acb3a0cdc1ff3f24c88229a811364839d0bb9bf0de66fead29c8d8b0aa034cd6e5bb799c6fb37c57242@165.22.126.72:30303,enode://6ab71d2e306d97801d248d6dc96197d39f9ab850a894b009ddfc14d4e60c07d6cdb7a12bdbcdbec558477e7a11fc9a160074efc66a87868ff72b45bdda98c35a@142.93.38.53:30303,enode://474a13b60e62aabedc8aacd934e687f54786dec825a4a4e1ebeba1e5b66853341883cef5bc08a82a839ad1963fe068c08e81a66f66ca33dc7a1dd57efe388c78@143.244.142.41:30303
    volumes:
      - ./key:/root/data/keys/kitabu_sarafu/key
      - ./kitabu.json:/root/kitabu.json
      - ./kitabu.toml:/root/kitabu.toml
      - ./password:/root/password
      - ./data:/root/data
    expose:
      - '8545'
      - '8546'
    ports:
      - '30303:30303'
      - '30303:30303/udp'
    networks:
      - kitabu
networks:
  kitabu:
    driver: bridge
