version: '3.9'
services:
  openethereum:
    init: true
    user: root
    restart: unless-stopped
    container_name: kitabu-openethereum
    image: openethereum/openethereum:v3.3.3
    command:
      --config=/root/kitabu.toml
      --nat='extip:$EXT_IP'
      --engine-signer='$ACCOUNT'
      --jsonrpc-port=8545
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=web3,eth,net,parity
      --ws-port=8546
      --ws-interface=all
      --ws-hosts=all
      --bootnodes=enode://e1ac7badf3e461883d776539f0541a5f5f5a71acee3ff276c8252f4d018eefade0acfed97e365e140e0b7420c0b81960ee5afe0c4c30b29e6a6fe123dacf00e2@143.244.142.41:30303,enode://f4888f135705fe2f3419eeb5ebbdfa4355c05eaab13ce7ddc7051976038b8f33ad34bedcf6bea9403cfe1e509da5e3efb989305fd32b273abee276d4acdc4f64@165.22.126.72:30303,enode://d13d2726e003c1dadb5846b1ac4421a1d728d0a3ac66a2acb202a8b8316a187094ac4b9da0e87a4df4abb9db47606a88172f57bf00fab26a718e097cacd4745a@142.93.38.53:30303
    volumes:
      - ./key:/root/data/keys/kitabu_sarafu/key
      - ./kitabu.json:/root/kitabu.json
      - ./kitabu.toml:/root/kitabu.toml
      - ./password:/root/password
      - ./data:/root/data
    expose:
      - '8545'
      - '8546'
    ports:
      - '30303:30303'
      - '30303:30303/udp'
    networks:
      - kitabu
networks:
  kitabu:
    driver: bridge
